waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: False
      waypoint_pause_duration: 20
    goal_check_tolerance: 0.35
    goal_dist_tolerance: 0.35    
    yaw_goal_tolerance: 6.28           
    goal_reached_timeout: 5.0